# Generated by Django 4.1.6 on 2023-02-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("favorite", models.TextField()),
                ("internal_ref", models.CharField(max_length=100)),
                ("responsible", models.CharField(max_length=100)),
                ("barcode", models.CharField(max_length=100)),
                ("sales_price", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("product_type", models.TextField(max_length=100)),
                ("quantity_on_hand", models.IntegerField()),
                ("forcated_quantity", models.IntegerField()),
                ("activity", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
