# Generated by Django 4.1.6 on 2023-02-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.CharField(default="Normal", max_length=200)),
                ("order_reference", models.CharField(max_length=200)),
                ("vendor", models.CharField(max_length=200)),
                ("purchase_representative", models.CharField(max_length=200)),
                ("order_deadline", models.CharField(max_length=200)),
                ("activities", models.CharField(max_length=200)),
                ("source_document", models.CharField(max_length=200)),
                ("Total", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_company", models.BooleanField(default=True)),
                ("related_company", models.CharField(max_length=200)),
                ("address_type", models.CharField(max_length=200)),
                ("street", models.CharField(max_length=200)),
                ("zip", models.IntegerField()),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="activity",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="favorite",
            field=models.CharField(default="Normal", max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="internal_ref",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="product",
            name="responsible",
            field=models.CharField(max_length=200),
        ),
    ]
